version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
      
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
        
     # - run:
     #     name: run tests
     #     command: |
     #       . venv/bin/activate
     #       jupyter-nbconvert --execute Linear_Regression.ipynb
     #       mkdir -p test_reports
     #       mv Linear_Regression.html test_reports
        
      - run:
          name: kaggle
          command: |
            . venv/bin/activate
            export KAGGLE_USERNAME=huma97
            export KAGGLE_KEY=07da689b628af9dbee0f5965ba1cf10f
            kaggle competitions download titanic
            jupyter-nbconvert --execute Titanic.ipynb
            kaggle competitions submit titanic -f titanic-submission.csv -m "My submission messsage"
            
      #- store_artifacts:
      #    path: test_reports
      #    destination: test_reports
          
