version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
      
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python2 -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            jupyter-nbconvert --execute Linear_Regression.ipynb
            mkdir -p test_reports
            mv Linear_Regression.html test_reports
        
      - run:
          name: kaggle
          command: |
            . venv/bin/activate
            mkdir .kaggle
            mv kaggle.json .kaggle
            kaggle competitions download titanic
            jupyter --execute Titanic.ipynb
            kaggle competitions submit titanic -f titanic-submission.csv -m "My submission"
            
      - store_artifacts:
          path: test_reports
          destination: test_reports
          
