version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
      
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            jupyter-nbconvert --execute Linear_Regression.ipynb
            mkdir -p test_reports
            mv Linear_Regression.html test_reports
            
      - store_artifacts:
          path: test_reports
          destination: test_reports
          
